-- Tabele (TABLES)

CREATE TABLE CATEGORIES (
    ID D_ID NOT NULL,
    NAME D_NAME NOT NULL,
    DESCRIPTION D_DESCRIPTION
);

CREATE TABLE PRODUCTS (
    ID D_ID NOT NULL,
    NAME D_NAME NOT NULL,
    CATEGORY_ID INTEGER,
    CREATED_BY INTEGER
);

CREATE TABLE USERS (
    ID D_ID NOT NULL,
    USERNAME D_NAME NOT NULL,
    EMAIL D_NAME,
    CREATED_AT D_DATETIME
);

