CREATE PROCEDURE GET_USER_BY_ID (P_ID INTEGER)
RETURNS (O_USERNAME VARCHAR(100), O_EMAIL VARCHAR(100))
AS
BEGIN
    SELECT USERNAME, EMAIL
    FROM USERS
    WHERE ID = :P_ID
    INTO :O_USERNAME, :O_EMAIL;
    SUSPEND;
END